### PR TITLE
Fixes missing cookies and data fields in get and json fields

### PR DESCRIPTION
**Pull request by camilopayan**
Replicates an existing patch for the 6.x branch here: https://github.com/laravel/browser-kit-testing/commit/a5524f33d9f2e803a22f2762d3a6428b63d3cee4

Since the 5.0 branch is the branch that supports Laravel 6, the LTS release, this should be merged in.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Only the framework repo is LTS, and not any of the other repos.

**Comment by camilopayan** [comment]
Is that the only thing keeping this from being merged in? The patch is exactly the same as the bugfix merged into the 6.x branch.

**Comment by GrahamCampbell** [comment]
Yes, the 5.x branch is EOL.

**Comment by driesvints** [comment]
Please upgrade to 6.x

**Comment by camilopayan** [comment]
Sure, should I submit a fix to the composer file to make the 6.x branch support Laravel 6 or was there an incompatibility introduced in the 6.x branch of this project?

**Pull request closed without merging**
