### PR TITLE
[5.x] Copied #30101

### PR DESCRIPTION
**Pull request by bytestream**
Copied laravel/framework#30101 here

### CODE REVIEW

**Comment by driesvints** [comment]
@bytestream it's always best that you also add an explanation instead of linking to an issue/pr. See the PR template.

**Comment by bytestream** [comment]
I think the linked PR provides a more than adequate explanation of why the functionality is beneficial. This PR simply copies it's work. There's not much more that can be said.

The use of traits in `Illuminate\Foundation\Testing` and this package make it difficult to reuse the functionality added by that PR. I'd rather not have to pull in both traits and write a long list of conflict resolutions for every conflicting method.

**Comment by jshah4517** [comment]
@driesvints Is it possible to have a new 5.x release including this?

**Comment by driesvints** [comment]
@jshah4517 I'll try to look into this next week.

**Pull request merged**
