### PR TITLE
Allow PHPUnit 9

### PR DESCRIPTION
**Pull request by crynobone**
Also update minimum PHPUnit version to follow Laravel 7 deps.

Signed-off-by: Mior Muhammad Zaki <crynobone@gmail.com>

### CODE REVIEW

**Comment by driesvints** [comment]
Can we also allow this on 5.x for people on Laravel 6.x?

**Comment by crynobone** [comment]
> Can we also allow this on 5.x for people on Laravel 6.x?

I'm a bit worried that someone using Laravel 5.x will end up getting PHPUnit 9 and get error with deprecated methods.

**Comment by driesvints** [comment]
@crynobone but won't they get the same than on this version? There's no other changes here than the bumped dependency.

**Comment by crynobone** [comment]
Laravel 5.x doesn't have https://github.com/laravel/framework/blob/6.x/src/Illuminate/Foundation/Testing/Assert.php

**Comment by driesvints** [comment]
@crynobone you're correct. Thanks!

**Pull request merged**
